giant case/esac for older chromedriver/chrome

diff --git a/src/commands/install-chromedriver.yml b/src/commands/install-chromedriver.yml
--- a/src/commands/install-chromedriver.yml
+++ b/src/commands/install-chromedriver.yml
@@ -25,24 +25,71 @@ steps:
 
         CHROME_VERSION_STRING="$(echo $CHROME_VERSION | sed 's/^Google Chrome //' | sed 's/^Chromium //')"
 
-        echo "Installed version of Google Chrome is $CHROME_VERSION_STRING"
+        echo "Installed version of Google Chrome/Chromium is $CHROME_VERSION_STRING"
 
         # determine chromedriver release
         CHROMEDRIVER_RELEASE="${CHROME_VERSION_STRING%%.*}"
 
-        echo "Corresponding Chromedriver release is $CHROMEDRIVER_RELEASE"
+        let CHROME_RELEASE=$CHROMEDRIVER_RELEASE
 
-        CHROMEDRIVER_VERSION=$(curl --silent --show-error --location --fail --retry 3 \
-          "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROMEDRIVER_RELEASE")
+        if [[ $CHROME_RELEASE -lt 70]]; then
+          # https://sites.google.com/a/chromium.org/chromedriver/downloads
+          # https://chromedriver.storage.googleapis.com/2.40/notes.txt
+          case $CHROME_RELEASE in
+          69)
+            CHROMEDRIVER_VERSION="2.44";;
+          68)
+            CHROMEDRIVER_VERSION="2.42";;
+          67)
+            CHROMEDRIVER_VERSION="2.41";;
+          66)
+            CHROMEDRIVER_VERSION="2.40";;
+          65)
+            CHROMEDRIVER_VERSION="2.38";;
+          64)
+            CHROMEDRIVER_VERSION="2.37";;
+          63)
+            CHROMEDRIVER_VERSION="2.36";;
+          62)
+            CHROMEDRIVER_VERSION="2.35";;
+          61)
+            CHROMEDRIVER_VERSION="2.34";;
+          60)
+            CHROMEDRIVER_VERSION="2.33";;
+          59)
+            CHROMEDRIVER_VERSION="2.32";;
+          58)
+            CHROMEDRIVER_VERSION="2.31";;
+          [56-57])
+            CHROMEDRIVER_VERSION="2.29";;
+          55)
+            CHROMEDRIVER_VERSION="2.28";;
+          54)
+            CHROMEDRIVER_VERSION="2.27";;
+          53)
+            CHROMEDRIVER_VERSION="2.26";;
+          52)
+            CHROMEDRIVER_VERSION="2.24";;
+          51)
+            CHROMEDRIVER_VERSION="2.23";;
+          [49-50])
+            CHROMEDRIVER_VERSION="2.22";;
+          [46-48])
+            CHROMEDRIVER_VERSION="2.21";;
+          [43-45])
+            CHROMEDRIVER_VERSION="2.20";;
+          *)
+            echo "Sorry, Google Chrome/Chromium version 43 or newer is required to use Chromedriver"
+            exit 1;;
+          esac
+        else
+          CHROMEDRIVER_VERSION=$(curl --silent --show-error --location --fail --retry 3 \
+            "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROMEDRIVER_RELEASE")
+        fi
 
         echo "Chromedriver $CHROMEDRIVER_VERSION will be installed"
 
         if false; then
-          # determine chromedriver release
-          CHROMEDRIVER_RELEASE="${CHROME_VERSION_STRING%%.*}"
-          CHROMEDRIVER_VERSION=$(curl --location --fail --retry 3 \
-            "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROMEDRIVER_RELEASE")
-
           # download chromedriver
           curl --silent --show-error --location --fail --retry 3 \
             --output chromedriver_linux64.zip \
