try installs on oracle

diff --git a/src/commands/install-chrome.yml b/src/commands/install-chrome.yml
--- a/src/commands/install-chrome.yml
+++ b/src/commands/install-chrome.yml
@@ -35,7 +35,6 @@ steps:
             $SUDO rm -rf /Applications/Google\ Chrome.app<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>> || true<</parameters.replace-existing>><<^parameters.replace-existing>>echo "$(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version)is already installed"
 
             exit 0<</parameters.replace-existing>>
-
           else
             echo "Google Chrome is not currently installed; installing it"
           fi
@@ -52,16 +51,28 @@ steps:
           else
             echo "Google Chrome (via Chromium) is not currently installed; installing it"
           fi
+        elif command -v yum<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
+          if command -v google-chrome<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
+            <<#parameters.replace-existing>>echo "$(google-chrome --version)is currently installed; replacing it"
+
+            $SUDO yum remove -y google-chrome-stable<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>> || true
+
+            $SUDO rm -f "$(command -v google-chrome)"<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>> || true<</parameters.replace-existing>><<^parameters.replace-existing>>echo "$(google-chrome --version)is already installed to $(which google-chrome)"
+
+            exit 0<</parameters.replace-existing>>
+          else
+            echo "Google Chrome is not currently installed; installing it"
+          fi
         else
           if command -v google-chrome<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
 
             <<#parameters.replace-existing>>echo "$(google-chrome --version)is currently installed; replacing it"
 
             $SUDO apt-get -y --purge remove google-chrome-stable<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>> || true
+
             $SUDO rm -f "$(command -v google-chrome)"<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>> || true<</parameters.replace-existing>><<^parameters.replace-existing>>echo "$(google-chrome --version)is already installed to $(which google-chrome)"
 
             exit 0<</parameters.replace-existing>>
-
           else
             echo "Google Chrome is not currently installed; installing it"
           fi
@@ -111,11 +122,36 @@ steps:
             echo "Something went wrong; Google Chrome could not be installed"
             exit 1
           fi
-        else
+        elif command -v yum<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
+          if cat /proc/version | grep amd64<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
+            ARCH=amd64
+          elif cat /proc/version | grep x86_64<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
+            ARCH=x86_64
+          fi
+
           # download chrome
           curl --silent --show-error --location --fail --retry 3 \
-            --output google-chrome-stable_current_amd64.deb \
-            https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
+            --output "google-chrome-stable_current_$ARCH.rpm" \
+            "https://dl.google.com/linux/direct/google-chrome-stable_current_$ARCH.rpm"
+
+          $SUDO yum localinstall -y "google-chrome-stable_current_$ARCH.rpm"<<^parameters.debug>> \
+            > /dev/null 2>&1<</parameters.debug>>
+
+          $SUDO yum upgrade -y google-chrome-stable<<^parameters.debug>> \
+            > /dev/null 2>&1<</parameters.debug>>
+
+          rm -rf "google-chrome-stable_current_$ARCH.rpm"
+        else
+          if cat /proc/version | grep amd64<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
+            ARCH=amd64
+          elif cat /proc/version | grep x86_64<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
+            ARCH=x86_64
+          fi
+
+          # download chrome
+          curl --silent --show-error --location --fail --retry 3 \
+            --output "google-chrome-stable_current_$ARCH.deb" \
+            "https://dl.google.com/linux/direct/google-chrome-stable_current_$ARCH.deb"
 
           $SUDO apt-get update<<^parameters.debug>> \
           > /dev/null 2>&1<</parameters.debug>> && \
@@ -150,16 +186,16 @@ steps:
 
           # setup chrome installation
           $SUDO dpkg -i \
-            google-chrome-stable_current_amd64.deb<<^parameters.debug>> \
+            "google-chrome-stable_current_$ARCH.deb"<<^parameters.debug>> \
             > /dev/null 2>&1<</parameters.debug>>
 
-          rm -rf google-chrome-stable_current_amd64.deb
+          rm -rf "google-chrome-stable_current_$ARCH.deb"
+        fi
 
-          # test/verify installation
-          if google-chrome --version<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
-            echo "$(google-chrome --version) has been installed to $(which google-chrome)"
-          else
-            echo "Something went wrong; Google Chrome could not be installed"
-            exit 1
-          fi
+        # test/verify installation
+        if google-chrome --version<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
+          echo "$(google-chrome --version) has been installed to $(which google-chrome)"
+        else
+          echo "Something went wrong; Google Chrome could not be installed"
+          exit 1
         fi
diff --git a/src/commands/install-chromedriver.yml b/src/commands/install-chromedriver.yml
--- a/src/commands/install-chromedriver.yml
+++ b/src/commands/install-chromedriver.yml
@@ -10,7 +10,8 @@ parameters:
     type: string
     default: /usr/local/bin
     description: >
-      Directory in which to install ChromeDriver
+      Directory in which to install ChromeDriver (directory selection
+      not supported on Alpine Linux)
 
   debug:
     type: boolean
@@ -25,12 +26,12 @@ steps:
         if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
 
         # determine_chrome_version
-        if uname -a | grep Darwin > /dev/null 2>&1; then
+        if uname -a | grep Darwin<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
           CHROME_VERSION="$(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version)"
           PLATFORM=mac64
 
-        elif cat /etc/issue | grep Alpine > /dev/null 2>&1; then
-          apk update > /dev/null 2>&1 && \
+        elif cat /etc/issue | grep Alpine<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
+          apk update<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>> && \
             apk add --no-cache chromium-chromedriver > /dev/null
 
           # verify version
@@ -44,7 +45,8 @@ steps:
 
         CHROME_VERSION_STRING="$(echo $CHROME_VERSION | sed 's/^Google Chrome //' | sed 's/^Chromium //')"
 
-        echo "Installed version of Google Chrome/Chromium is $CHROME_VERSION_STRING"
+        # print Chrome version
+        echo "Installed version of Google Chrome is $CHROME_VERSION_STRING"
 
         # determine chromedriver release
         CHROMEDRIVER_RELEASE="${CHROME_VERSION_STRING%%.*}"
@@ -108,8 +110,8 @@ steps:
         fi
 
         # installation check
-        if command -v chromedriver > /dev/null 2>&1; then
-          if chromedriver --version | grep "$CHROMEDRIVER_VERSION" > /dev/null 2>&1; then
+        if command -v chromedriver<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
+          if chromedriver --version | grep "$CHROMEDRIVER_VERSION"<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
             echo "ChromeDriver $CHROMEDRIVER_VERSION is already installed"
             exit 0
           else
@@ -126,11 +128,16 @@ steps:
           "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_$PLATFORM.zip"
 
         # setup chromedriver installation
-        unzip "chromedriver_$PLATFORM.zip" > /dev/null 2>&1
+        unzip "chromedriver_$PLATFORM.zip"<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>
         rm -rf "chromedriver_$PLATFORM.zip"
 
         $SUDO mv chromedriver <<parameters.install-dir>>
         $SUDO chmod +x <<parameters.install-dir>>/chromedriver
 
-        # verify version
-        echo "$(chromedriver --version) has been installed to $(which chromedriver)"
+        # test/verify version
+        if chromedriver --version | grep "$CHROMEDRIVER_VERSION"<<^parameters.debug>> > /dev/null 2>&1<</parameters.debug>>; then
+          echo "$(chromedriver --version) has been installed to $(which chromedriver)"
+        else
+          echo "Something went wrong; ChromeDriver could not be installed"
+          exit 1
+        fi
